version: '3'

services:
  TestForAssignment:
    image: 'netanel97/insait_assignment'
    ports:
      - "5000:5000"
    networks:
      - "network1"
    depends_on:
      - postgres
    command: ["bash", "-c", "python ./application.py && alembic upgrade head"]

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=123123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - "network1"


networks:
  network1:
    name: "network1"
