version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always
    environment:
      - RUN_TESTS=false  # Ensure this service runs the application

  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=<YOUR_POSTGRES_DB_NAME>
      - POSTGRES_PASSWORD=<YOUR_POSTGRES_PASSWORD>
      - POSTGRES_USER=<YOUR_POSTGRES_USER_NAME>
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - RUN_TESTS=true  # Ensure this service runs the tests
    command: pytest --disable-warnings  # Override the command to run tests

volumes:
  postgres_data:
