version: '3'

services:
  test_for_assignment:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: 'postgres:latest'
    env_file: # Load environment variables from .env file
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: